version: "3.9"  
services:
  db:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: "root"
        MONGO_INITDB_ROOT_PASSWORD: "password"
  jaeger:
    image: jaegertracing/all-in-one:1.32
    ports:
      - "14268:14268"   # jaeger-collector HTTP server (tracer provider)
      - "16686:16686"   # HTTP server (browser UI)
