version: "3.9"  
services:
  db:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: "root"
        MONGO_INITDB_ROOT_PASSWORD: "password"
  users:
    build:
      context: .
    environment:
      RPC_PORT: 8080
      HEALTH_PORT: 9090
      DATABASE_URI: mongodb://root:password@db:27017/users?authSource=admin
    ports:
      - "8080:8080"
      - "9090:9090"



