name: Go

on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:5.0
        ports:
          - "27017:27017"
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password
          
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Lint
      run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          make lint

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...