name: Go

on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Lint
        - run: |
            go install honnef.co/go/tools/cmd/staticcheck@latest
            make lint

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...